site_name: pytest-testobject
site_description: Plugin to use TestObject Suites with Pytest
site_author: Enrique Gonzalez

theme: readthedocs

repo_url: https://github.com/enriquegh/pytest-testobject

pages:
- Home: index.md
copyright: Copyright &copy; 2017 <a href="https://github.com/enriquegh">Enrique Gonzalez</a>